default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: frontdhionux
  password: dhionux11235813
  host: localhost

development:
  <<: *default
  database: meu_app_postgres_development

test:
  <<: *default
  database: meu_app_postgres_test

production:
  <<: *default
  database: meu_app_postgres_production
  username: frontdhionux
  password: <%= ENV["MEU_APP_DATABASE_PASSWORD"] || "dhionux11235813" %>
